#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
.gitignore 生成器 - 全面版
用法:
    python gitignore_gen.py                     # 交互式选择模板
    python gitignore_gen.py --list              # 列出所有可用模板
    python gitignore_gen.py python macos vscode # 合并指定模板
    python gitignore_gen.py --detect            # 自动检测并推荐模板
    python gitignore_gen.py --custom "*.log" "temp/"  # 添加自定义规则
"""

import os
import sys
import argparse
from pathlib import Path

# ---------- 模板库 ----------
TEMPLATES = {}

# Python
TEMPLATES['python'] = '''# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Virtual environments
venv/
env/
ENV/
env.bak/
venv.bak/
.venv/

# IDE
.idea/
.vscode/
*.swp
*.swo

# Testing
.pytest_cache/
.coverage
htmlcov/
.tox/
.mypy_cache/
.ruff_cache/

# Jupyter Notebook
.ipynb_checkpoints

# Environment variables
.env
.env.local
.env.*.local

# Logs and databases
*.log
*.sql
*.sqlite
*.db

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
desktop.ini
'''

# Node.js / JavaScript
TEMPLATES['node'] = '''# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Dependency directories
node_modules/
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build output
.nuxt
dist

# Gatsby files
.cache/
public

# Storybook build output
storybook-static

# tmp folders
tmp/
temp/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
'''

# Java
TEMPLATES['java'] = '''# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java
.mtj.tmp/

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# virtual machine crash logs
hs_err_pid*
replay_pid*

# IDE
.idea/
*.iml
*.iws
*.ipr
.classpath
.project
.settings/
.vscode/
*.swp
*.swo

# Gradle
.gradle/
build/

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties

# OS
.DS_Store
Thumbs.db
'''

# Go
TEMPLATES['go'] = '''# Binaries
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary
*.test

# Output of the go coverage tool
*.out

# Dependency directories
vendor/

# Go workspace file
go.work
go.work.sum

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
'''

# Rust
TEMPLATES['rust'] = '''# Generated by Cargo
/target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# Cargo.lock

# MSVC Windows builds of rustc generate these
*.pdb

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
'''

# C / C++
TEMPLATES['cpp'] = '''# Prerequisites
*.d

# Compiled Object files
*.slo
*.lo
*.o
*.obj

# Precompiled Headers
*.gch
*.pch

# Compiled Dynamic libraries
*.so
*.dylib
*.dll

# Fortran module files
*.mod
*.smod

# Compiled Static libraries
*.lai
*.la
*.a
*.lib

# Executables
*.exe
*.exe~
*.out
*.app

# IDE
.idea/
.vscode/
*.swp
*.swo

# Build directories
build/
cmake-build-*/

# OS
.DS_Store
Thumbs.db
'''

# C#
TEMPLATES['csharp'] = '''# Build results
[Dd]ebug/
[Rr]elease/
x64/
x86/
[Bb]in/
[Oo]bj/

# Visual Studio
.vs/
*.user
*.userosscache
*.suo
*.userprefs
*.sln.docstates

# Rider
.idea/

# NuGet
packages/
*.nupkg

# OS
.DS_Store
Thumbs.db
'''

# Ruby
TEMPLATES['ruby'] = '''# Bundler
Gemfile.lock
*.gem

# Vendored gems
vendor/bundle/

# Ruby version
.ruby-version

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
'''

# PHP
TEMPLATES['php'] = '''# Composer
composer.phar
/vendor/

# PHPUnit
.phpunit.result.cache
/.phpunit.cache

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
'''

# Swift / iOS
TEMPLATES['swift'] = '''# Xcode
build/
*.xcuserstate
*.xcuserdata
*.xcworkspace
!default.xcworkspace
xcshareddata/
xcuserdata/
*.moved-aside
DerivedData/
*.hmap
*.ipa
*.dSYM.zip
*.dSYM

# Swift Package Manager
.build/
.swiftpm/

# CocoaPods
Pods/

# Carthage
Carthage/Build/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
'''

# Kotlin
TEMPLATES['kotlin'] = '''# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java
.mtj.tmp/

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# virtual machine crash logs
hs_err_pid*
replay_pid*

# Gradle
.gradle/
build/

# IntelliJ IDEA
.idea/
*.iml
*.iws
*.ipr
out/

# IDE
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
'''

# Unity
TEMPLATES['unity'] = '''# Unity
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/

# MemoryCaptures
/[Mm]emoryCaptures/

# Asset meta data should only be ignored when the corresponding asset is also ignored
!/[Aa]ssets/**/*.meta

# Autogenerated Jetbrains Rider plugin
/[Aa]ssets/Plugins/Editor/JetBrains*

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage

# Crashlytics
com_crashlytics_export_strings.xml

# OS
.DS_Store
Thumbs.db
'''

# macOS
TEMPLATES['macos'] = '''# General
.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two 
Icon

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk
'''

# Windows
TEMPLATES['windows'] = '''# Windows thumbnail cache
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db

# Dump file
*.stackdump
[Dd]esktop.ini
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

# Windows shortcuts
*.lnk
'''

# Linux
TEMPLATES['linux'] = '''# Linux temporary files
*~
.fuse_hidden*
.directory
.Trash-*
.nfs*
'''

# Django
TEMPLATES['django'] = '''# Django
*.log
*.pot
*.pyc
__pycache__/
local_settings.py
db.sqlite3
media/
staticfiles/
'''

# Flask
TEMPLATES['flask'] = '''# Flask
instance/
.webassets-cache
.env
'''

# Docker
TEMPLATES['docker'] = '''# Docker
.dockerignore
Dockerfile
docker-compose*.yml
*.tar
*.tar.gz
'''

# Vue
TEMPLATES['vue'] = '''# Vue
node_modules/
dist/
.DS_Store
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
.env.local
.env.*.local
'''

# React
TEMPLATES['react'] = '''# React
node_modules/
build/
.DS_Store
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.env.local
.env.*.local
'''

# Visual Studio Code
TEMPLATES['vscode'] = '''# VS Code
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace
'''

# IntelliJ IDEA
TEMPLATES['intellij'] = '''# IntelliJ IDEA
.idea/
*.iml
*.iws
*.ipr
out/
'''

# Eclipse
TEMPLATES['eclipse'] = '''# Eclipse
.classpath
.project
.settings/
bin/
'''

# Vim
TEMPLATES['vim'] = '''# Vim
*.swp
*.swo
*~
.*.un~
'''

# Emacs
TEMPLATES['emacs'] = '''# Emacs
*~
\#*\#
/.emacs.desktop
/.emacs.desktop.lock
*.elc
auto-save-list
tramp
.\#*
'''

# TeX / LaTeX
TEMPLATES['latex'] = '''# LaTeX
*.aux
*.bbl
*.blg
*.idx
*.ind
*.lof
*.lot
*.out
*.toc
*.acn
*.acr
*.alg
*.glg
*.glo
*.gls
*.ist
*.fls
*.log
*.fdb_latexmk
'''

# R
TEMPLATES['r'] = '''# R
.Rproj.user
.Rhistory
.RData
.Ruserdata
*.Rproj
'''


# ---------- 辅助函数 ----------
def list_templates():
    """列出所有可用模板"""
    print("可用的 .gitignore 模板:")
    for name in sorted(TEMPLATES.keys()):
        print(f"  - {name}")


def merge_templates(template_names):
    """合并多个模板的内容"""
    lines = []
    seen_lines = set()
    for name in template_names:
        if name not in TEMPLATES:
            print(f"警告: 模板 '{name}' 不存在，已跳过", file=sys.stderr)
            continue
        content = TEMPLATES[name].strip()
        for line in content.split('\n'):
            line = line.rstrip()
            # 简单去重（忽略空行和注释）
            if line and not line.startswith('#'):
                key = line.strip()
                if key in seen_lines:
                    continue
                seen_lines.add(key)
            lines.append(line)
        lines.append('')  # 模板间加空行
    return '\n'.join(lines).strip()


def detect_project():
    """自动检测当前项目可能需要的模板"""
    detected = set()
    cwd = Path.cwd()

    # 检测文件/目录特征
    if (cwd / 'requirements.txt').exists() or (cwd / 'setup.py').exists() or (cwd / 'pyproject.toml').exists():
        detected.add('python')
    if (cwd / 'package.json').exists():
        detected.add('node')
    if (cwd / 'pom.xml').exists() or (cwd / 'build.gradle').exists():
        detected.add('java')
    if (cwd / 'go.mod').exists():
        detected.add('go')
    if (cwd / 'Cargo.toml').exists():
        detected.add('rust')
    if (cwd / 'CMakeLists.txt').exists() or list(cwd.glob('*.cpp')) or list(cwd.glob('*.c')):
        detected.add('cpp')
    if (cwd / '*.csproj').exists() or (cwd / '*.sln').exists():
        detected.add('csharp')
    if (cwd / 'Gemfile').exists():
        detected.add('ruby')
    if (cwd / 'composer.json').exists():
        detected.add('php')
    if (cwd / '*.xcodeproj').exists() or (cwd / '*.xcworkspace').exists():
        detected.add('swift')
    if (cwd / 'manage.py').exists():
        detected.add('django')
    if (cwd / 'app.py').exists() or (cwd / 'application.py').exists():
        detected.add('flask')
    if (cwd / 'Dockerfile').exists():
        detected.add('docker')
    if (cwd / 'vue.config.js').exists() or (cwd / 'src' / 'App.vue').exists():
        detected.add('vue')
    if (cwd / '.vscode').exists():
        detected.add('vscode')
    if (cwd / '.idea').exists():
        detected.add('intellij')

    # 总是添加 OS 相关模板（但用户可以选择不加）
    # 这里不自动添加，让用户自己决定
    return detected


def interactive_select():
    """交互式选择模板"""
    print("可用的 .gitignore 模板:")
    templates_list = sorted(TEMPLATES.keys())
    for i, name in enumerate(templates_list, 1):
        print(f"{i:2}. {name}")
    print("0. 完成选择")
    print("例如: 输入 '1 3 5' 选择多个，或 'all' 全选")

    selected = []
    while True:
        choice = input("\n请选择模板编号（空格分隔）: ").strip()
        if choice == '0':
            break
        if choice.lower() == 'all':
            selected = templates_list.copy()
            break
        parts = choice.split()
        for part in parts:
            if part.isdigit():
                idx = int(part)
                if 1 <= idx <= len(templates_list):
                    selected.append(templates_list[idx - 1])
                else:
                    print(f"无效编号: {idx}")
            else:
                print(f"无效输入: {part}")
        if selected:
            break
    return selected


def custom_rules(rules_list):
    """将用户自定义规则格式化为文本"""
    if not rules_list:
        return ""
    lines = ["# Custom rules", ""]
    for rule in rules_list:
        lines.append(rule)
    return "\n".join(lines)


def write_gitignore(content, output_path='.gitignore', append=False):
    """写入 .gitignore 文件"""
    mode = 'a' if append else 'w'
    with open(output_path, mode, encoding='utf-8') as f:
        f.write(content)
        if not content.endswith('\n'):
            f.write('\n')
    print(f"已写入 {output_path}")


def main():
    parser = argparse.ArgumentParser(description='功能全面的 .gitignore 生成器')
    parser.add_argument('templates', nargs='*', help='要生成的模板名称（如 python node macos）')
    parser.add_argument('--list', '-l', action='store_true', help='列出所有可用模板')
    parser.add_argument('--detect', '-d', action='store_true', help='自动检测项目并推荐模板')
    parser.add_argument('--custom', '-c', nargs='+', metavar='RULE', help='添加自定义忽略规则（如 "*.log" "temp/"）')
    parser.add_argument('--append', '-a', action='store_true', help='追加到现有 .gitignore 文件（默认覆盖）')
    parser.add_argument('--output', '-o', default='.gitignore', help='输出文件路径（默认 .gitignore）')
    parser.add_argument('--interactive', '-i', action='store_true', help='交互式选择模板')
    args = parser.parse_args()

    if args.list:
        list_templates()
        return

    if args.detect:
        detected = detect_project()
        if detected:
            print("检测到项目可能需要的模板:")
            for name in sorted(detected):
                print(f"  - {name}")
            print("\n使用命令: python gitignore_gen.py " + " ".join(detected))
        else:
            print("未检测到已知项目特征，请手动选择模板。")
        return

    # 确定要使用的模板列表
    selected_templates = []
    if args.interactive:
        selected_templates = interactive_select()
    elif args.templates:
        selected_templates = args.templates
    else:
        # 无参数时默认交互模式
        selected_templates = interactive_select()

    if not selected_templates:
        print("未选择任何模板，退出。")
        return

    # 生成内容
    content = merge_templates(selected_templates)

    # 添加自定义规则
    if args.custom:
        custom_content = custom_rules(args.custom)
        if content:
            content += "\n\n" + custom_content
        else:
            content = custom_content

    if not content:
        print("警告: 生成的 .gitignore 内容为空。")
        return

    # 写入文件
    write_gitignore(content, args.output, args.append)

    # 输出摘要
    print(f"\n已合并模板: {', '.join(selected_templates)}")
    if args.custom:
        print(f"自定义规则: {', '.join(args.custom)}")


if __name__ == "__main__":
    main()