# Project: Ò»¸öcÓïÑÔÅÀ³æ
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = cÓïÑÔÅÀ³æ/Ò»¸ö³¢ÊÔ.o cÓïÑÔÅÀ³æ/Ò»¸öÅÀ³æ£¬c°æ.o
LINKOBJ  = cÓïÑÔÅÀ³æ/Ò»¸ö³¢ÊÔ.o cÓïÑÔÅÀ³æ/Ò»¸öÅÀ³æ£¬c°æ.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Ò»¸öcÓïÑÔÅÀ³æ.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

cÓïÑÔÅÀ³æ/Ò»¸ö³¢ÊÔ.o: cÓïÑÔÅÀ³æ/Ò»¸ö³¢ÊÔ.c
	$(CC) -c cÓïÑÔÅÀ³æ/Ò»¸ö³¢ÊÔ.c -o cÓïÑÔÅÀ³æ/Ò»¸ö³¢ÊÔ.o $(CFLAGS)

cÓïÑÔÅÀ³æ/Ò»¸öÅÀ³æ£¬c°æ.o: cÓïÑÔÅÀ³æ/Ò»¸öÅÀ³æ£¬c°æ.c
	$(CC) -c cÓïÑÔÅÀ³æ/Ò»¸öÅÀ³æ£¬c°æ.c -o cÓïÑÔÅÀ³æ/Ò»¸öÅÀ³æ£¬c°æ.o $(CFLAGS)
